### ISSUE TITLE
Class chrmorandi\jasper does not exist

### ISSUE THREAD

**Issue by claudiogg88** [chrmorandi/yii2-jasper#1]
i can not run hello word example.

Class chrmorandi\jasper does not exist

thanks.

**Comment by mrisho** [comment]
Yeah, I am getting the same thing

**Comment by lorenzokniss** [comment]
Try this: 'class' => \chrmorandi\jasper\Jasper::classname().

:)

**Comment by mrisho** [comment]
I did it but I got another error "Your report has an error and couldn't be processed! Try to output the command: /var/www/html/myreports/vendor/chrmorandi/yii2-jasper/src/Jasper/../JasperStarter/bin/jasperstarter process /var/www/html/myreports/vendor/chrmorandi/yii2-jasper/examples/hello_world.jrxml -f pdf rtf -P REPORT_LOCALE=pt_BR php_version=5.5.9-1ubuntu4.19 -t mysql -u root -p allpasswords -H myhost -n mydatabase --db-port 3306"

**Comment by lorenzokniss** [comment]
Try run this command in your terminal and you'll get the specific error :)

Your report is waiting the parameters that you're sending ("REPORT_LOCALE" and "php_version") ?

**Comment by mrisho** [comment]
I tried, it compiles in a command but not in my application. It also creates pdf in a command but  not in my application. What could be wrong?
