### ISSUE TITLE
Hi get this error:

### ISSUE THREAD

**Issue by dezysbg** [chrmorandi/yii2-jasper#3]
I got this erroe when executed it:
Your report has an error and couldn't be processed! Try to output the command: C:^^^\xampp^^^\htdocs^^^\www^^^\vitrudevRBAC^^^\vendor^^^\chrmorandi^^^\yii2-jasper^^^\src^^^\Jasper/../JasperStarter/bin/jasperstarter compile C:^^^\xampp^^^\htdocs^^^\www^^^\vitrudevRBAC/vendor/chrmorandi/yii2-jasper/examples/hello_world.jrxml

could you please help me?

**Comment by whmemon** [comment]
I am also getting same error. How to fix it ?
